### ISSUE TITLE
ConsoleExtensions not needed

### ISSUE THREAD

**Issue by SadConsole** [deengames/ali-the-android#3]
I saw your code there and just FYI the `console.SetGlyph` method has overloads for everything you're doing in there, you don't need your `DrawCharacter` methods at all. 

[SetGlyph(x, y, glyph, foreground, background) reference](http://sadconsole.com/api/SadConsole.CellSurface.html#SadConsole_CellSurface_SetGlyph_System_Int32_System_Int32_System_Int32_Microsoft_Xna_Framework_Color_Microsoft_Xna_Framework_Color_)

**Comment by nightblade9** [comment]
Thanks for this, It's all prototype code right now, but I will update it at some point to use `SetGlyph` instead.
